Repository fga-eps-mds/2024.2-ARANDU-UserService, pull requests merged in 2025-01, with the labels that each got.

#20 [FIX] Substitui atributo 'id' por 'userId' no payload do JWT (fga-eps-mds/2024.2-ARANDU-DOC#110)
  src/auth/auth.service.ts
  test/auth.controller.spec.ts
  test/auth.service.spec.ts
Labels: bug, FIX RELEASE

#21 [FIX] Remove role CreateUserDto (fga-eps-mds/2024.2-ARANDU-DOC#100)
  src/dtos/create-user.dto.ts
  src/users/users.service.ts
Labels: bug, FIX RELEASE

#22 [FIX] Corrige bugs de criação de usuários admins e userId no token
  src/auth/auth.service.ts
  src/dtos/create-user.dto.ts
  src/users/users.service.ts
  test/auth.controller.spec.ts
  test/auth.service.spec.ts
Labels: FIX RELEASE

#23 [FIX] Remoção de loggers (fga-eps-mds/2024.2-ARANDU-DOC#108)
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/strategies/google.strategy.ts
  src/auth/strategies/microsoft.strategy.ts
Labels: bug, FIX RELEASE

#24 [FIX] Remove exibição de dados pessoais no console (fga-eps-mds/2024.2-ARANDU-DOC#108)
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/strategies/google.strategy.ts
  src/auth/strategies/microsoft.strategy.ts
Labels: MINOR RELEASE

#25 [RELEASE] Introduz correções gerais no backend
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/guards/auth.guard.ts
  src/auth/strategies/google.strategy.ts
  src/auth/strategies/microsoft.strategy.ts
  src/dtos/create-user.dto.ts
  src/dtos/update-user.dto.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.ts
  test/auth.controller.spec.ts
  test/auth.service.spec.ts
  test/user.controller.spec.ts
  test/user.service.spec.ts
Labels: bug, MINOR RELEASE

#26 [FIX] Adiciona atributo ID ao JWT (fga-eps-mds/2024.2-ARANDU-DOC#112)
  src/auth/auth.service.ts
Labels: bug, FIX RELEASE

#27 [TEST] Corrige testes do AuthService e AuthController (fga-eps-mds/2024.2-ARANDU-DOC#112)
  test/auth.controller.spec.ts
  test/auth.service.spec.ts
Labels: bug

#28 [FIX] Adiciona atributo ID ao JWT (fga-eps-mds/2024.2-ARANDU-DOC#112)
  src/auth/auth.service.ts
  test/auth.controller.spec.ts
  test/auth.service.spec.ts
Labels: bug, FIX RELEASE

#33 [FEAT] Adiciona username ao token (fga-eps-mds/2024.2-ARANDU-DOC#59)
  package.json
  src/auth/auth.service.ts
  src/users/interface/user.interface.ts
  src/users/interface/user.schema.ts
  src/users/users.controller.ts
  src/users/users.service.ts
  test/auth.controller.spec.ts
  test/auth.service.spec.ts
  test/user.controller.spec.ts
  test/user.service.spec.ts
Labels: MINOR RELEASE
